# Generated by Django 4.0.2 on 2022-02-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tranding',
            new_name='trending',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tranding',
            new_name='trending',
        ),
    ]
