# Generated by Django 4.0.2 on 2022-02-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_tranding_category_trending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='trending',
            field=models.BooleanField(default=False, help_text='0 = Default, 1 = Trending '),
        ),
        migrations.AlterField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False, help_text='0 = Default, 1 = Trending '),
        ),
    ]
