# Generated by Django 4.0.2 on 2022-02-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_status_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Out for Shipping', 'Out for Shipping'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
