# Generated by Django 4.0.2 on 2022-02-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_docs_event_doc_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='doc',
            new_name='docs',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for Shipping', 'Out for Shipping'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
    ]
