# Generated by Django 4.0.2 on 2022-02-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_event_aboutevent_alter_event_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ending_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Out for Shipping', 'Out for Shipping'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
