# Generated by Django 4.0.2 on 2022-02-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_event_ending_date_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='aboutEvent',
            field=models.CharField(choices=[('aboutUS', 'aboutUS'), ('announcement', 'announcement')], default='announcement', max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for Shipping', 'Out for Shipping'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
    ]
