# Generated by Django 4.0.2 on 2022-02-09 13:15

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_image_event_image1_event_image2_event_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='aboutEvent',
            field=models.CharField(choices=[('aboutUS', 'aboutUS'), ('announcement', 'announcement')], default='announcement', max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Out for Shipping', 'Out for Shipping'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
