# Generated by Django 4.0.2 on 2022-02-10 07:30

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_discountevent_alter_order_status_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Shipping', 'Out for Shipping'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=store.models.get_file_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path)),
                ('link', models.URLField(blank=True, null=True)),
                ('docs', models.FileField(blank=True, upload_to=store.models.get_doc_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
